### ISSUE TITLE
 Fails to download composer dependencies

### ISSUE THREAD

**Issue by lucianpricop** [totten/loco#2]
Hi Tim,
Your packages seem awesome and help a lot in the wilderness of what nix is. However I say seem because I can't get loco to work. I am coming from locolamp which I had to tweak because I need php7.4 but I can't continue with loco because it fails with the first composer dependency:

`Package operations: 16 installs, 0 updates, 0 removals
  - Installing togos/gitignore (1.1.1): Downloading (failed)
Downloading (failed)
Downloading (failed)    Failed to download togos/gitignore from dist: The "https://api.github.com/repos/TOGoS/PHPGitIgnore/zipball/32bc0830e4123f670adcbf5ddda5bef362f4f4d4" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known
    Now trying to download from source
  - Installing togos/gitignore (1.1.1): Cloning 32bc0830e4

  [RuntimeException]
  Failed to clone https://github.com/TOGoS/PHPGitIgnore.git, git was not found, check that it is installed and in your PATH env.

  sh: git: not found
`
Do you have any idea why? I am running with nix-build, am I'm not on nixos:

server: Ubuntu 18.04.4 LTS \n \l

nix-shell (Nix) 2.5.1

**Comment by totten** [comment]
@lucianpricop Apologies, I didn't see this ping before. Hopefully found a resolution. FWIW:

> sh: git: not found

I think this means that the environment in which it is building needs to have the `git` package. Perhaps it's an omission that needs to be added around these lines:

https://github.com/totten/loco/blob/master/default.nix#L47
https://github.com/totten/loco/blob/master/default.nix#L8

**Comment by totten** [comment]
I did a trial-run to try to force it to produce the same error, but I couldnt'.

```
cd loco
nix-shell --pure
git --version
## Shows the command is missing
rm -rf vendor
composer install
## Runs OK - composer shouldn't usually need to download via `git`
```

Here's a revised theory... the error started with:

>  Downloading (failed) Failed to download togos/gitignore from dist: The "https://api.github.com/repos/TOGoS/PHPGitIgnore/zipball/32bc0830e4123f670adcbf5ddda5bef362f4f4d4" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known

This shows the download failing. It may be happenstance that `togos/gitignore` is the first dependency that it tried to download -- and that it was hosted on Github -- and that Github was unavailable. Github outages don't happen every day... but they do happen a few times a year...

Since `composer` failed to download via `https://`, it may have used a fallback to another protocol (eg `git://`). And that's when it raised `sh: git: not found`.

In that theory, we may not really need any change - since the issue was really Github hosting.

I guess the question is whether the problem is still occurring. (Github hosting outages are usually temporary...) If it is still occurring, then (theoretically) a patch like this might alleviate the symptom (by allowing the fallback to work):

```diff
diff --git a/default.nix b/default.nix
index 2d27152..ba07476 100644
--- a/default.nix
+++ b/default.nix
@@ -5,7 +5,8 @@
   system ? builtins.currentSystem,
   noDev ? false,
   php ? pkgs.php72,
-  phpPackages ? pkgs.php72Packages
+  phpPackages ? pkgs.php72Packages,
+  git ? pkgs.git
   }:
 
 let
@@ -44,7 +45,7 @@ in stdenv.mkDerivation rec {
     #  sha256 = "FIXME";
     #};
 
-    buildInputs = [ php phpPackages.composer phpPackages.box ];
+    buildInputs = [ git php phpPackages.composer phpPackages.box ];
     builder = "${src}/scripts/nix-builder.sh";
     shellHook = ''
       PATH="$PWD/bin:$PWD/extern:$PATH"
```

**Comment by lucianpricop** [comment]
Thank you for taking the time to look into it. I gave up on nix for good, so will not be able to check. All the best!
